language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - sudo apt-get -y update
  - sudo apt-get -y install tcl tcl-dev
  - if [ "$CXX" = "g++" ]; then echo sudo apt-get -y install libcppunit-dev libcppunit-1.13-0; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get -y install gcc-6 g++-6; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get -y install clang-3.6; fi
  - if [ "$CXX" = "clang++" ]; then svn co --quiet --trust-server-cert --non-interactive https://llvm.org/svn/llvm-project/libcxxabi/trunk@r249649 libcxxabi; fi
  - if [ "$CXX" = "clang++" ]; then svn co --quiet --trust-server-cert --non-interactive https://llvm.org/svn/llvm-project/libcxx/trunk@r249595 libcxx; fi
  - if [ "$CXX" = "clang++" ]; then (cd libcxx/lib && env CXX="clang++-3.6 -I ../../libcxxabi/include" sh buildit); fi
  - if [ "$CXX" = "clang++" ]; then sudo cp libcxx/lib/libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" = "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" = "clang++" ]; then sudo cp -r libcxx/include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" = "clang++" ]; then sudo ln -sf libc++.so.1.0 /usr/lib/libc++.so; fi
  - if [ "$CXX" = "clang++" ]; then sudo ln -sf libc++.so.1.0 /usr/lib/libc++.so.1; fi
  - if [ "$CXX" = "clang++" ]; then (cd libcxxabi/lib && env CXX="clang++-3.6 -I ../../libcxx/include" sh buildit); fi
  - if [ "$CXX" = "clang++" ]; then sudo cp libcxxabi/lib/libc++abi.so.1.0 /usr/lib/; fi
  - if [ "$CXX" = "clang++" ]; then sudo ln -sf libc++abi.so.1.0 /usr/lib/libc++abi.so; fi
  - if [ "$CXX" = "clang++" ]; then sudo ln -sf libc++abi.so.1.0 /usr/lib/libc++abi.so.1; fi
  - if [ "$CXX" = "clang++" ]; then export CXXFLAGS="-stdlib=libc++" CPPUNIT_CFLAGS="-stdlib=libc++" LDFLAGS="-stdlib=libc++ -lc++abi"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  - (wget http://dev-www.libreoffice.org/src/cppunit-1.14.0.tar.gz && tar -zxvf cppunit-1.14.0.tar.gz && cd cppunit-1.14.0 && ./configure --prefix=/usr --disable-doc --disable-doxygen --disable-html-docs && make -j2 V=1 && sudo make install)
  - export CPPFLAGS="-D_FORTIFY_SOURCE=2"
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# Skip install
install: true

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then ./configure; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then make -j2 V=1; fi
  - if [ "${COVERITY_SCAN_BRANCH}" != "1" ]; then make -j2 test V=1; fi

# Coverity configuration
env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "kyAOuW9+HUbGel/mzT9rMP7gUcduUwpg6x0UjGEVgAMkv3vxRnF1ZMh2Bgcrna59IDzsacULkelDBm0+6hqEMJYmyWhb6vtwt40TLszBMFKku9Y1S1JQzyX9wvsiWC8OK2fzhbH36c45OaA0Eu9DrBg2FNQ7ZKyQkHBjhyagU8o="

addons:
  coverity_scan:
    project:
      name: "wraith/wraith"
      description: "Build submitted via Travis CI"
    notification_email: bryan-coverity@shatow.net
    build_command_prepend: "cov-configure --comptype g++ --compiler g++-6 --template; ./configure"
    build_command: "make -j2 V=1"
    branch_pattern: coverity_scan

# State we need old build infrastructure for now
sudo: required
dist: trusty
